import type { Language, UiCopy } from "./types";

export const uiCopy: Record<Language, UiCopy> = {
  en: {
    locale: {
      time: "en-US",
      date: "en-US",
      duration: "en-US",
    },
    header: {
      locationLabel: "Location:",
      navigationLabel: "Navigation:",
      themeLabel: "Theme:",
      languageLabel: "Language:",
      menuLabel: "Menu",
      closeLabel: "Close",
      lightModeLabel: "Light Mode",
      darkModeLabel: "Dark Mode",
      navigationLinks: [
        { to: "/", label: "Home" },
        { to: "/Contact", label: "Contact" },
        { to: "/Project", label: "Projects" },
      ],
    },
    home: {
      about: {
        line1Prefix: "I'm ",
        line1Highlight: "Darinel",
        line1Suffix: ",",
        line2Prefix: "a ",
        line2Highlight: "versatile software engineer",
        line2Suffix: "",
        line3Prefix: "who enjoys ",
        line3Highlight: "full-stack development",
        line3Suffix: "",
        line4Prefix: "and ",
        line4Highlight: "problem-solving",
        line4Suffix: ".",
        notePrefix: "Always eager to ",
        noteHighlightOne: "learn and grow",
        noteMiddle: ", I thrive on tackling ",
        noteHighlightTwo: "new challenges",
        noteSuffix: " and expanding my skill set.",
      },
      skills: {
        titlePrefix: "My",
        titleHighlight: "Skills",
        subtitle: "The tech stack I use to build solutions",
        sectionTitles: {
          technical_skills: "Technical Skills",
          devOps: "DevOps",
          databases: "Databases",
          mobile_development: "Mobile Development",
          backend_development: "Backend Development",
          frontend_development: "Frontend Development",
          tools: "Tools",
          soft_skills: "Soft Skills",
          languages: "Languages",
          certifications: "Certifications",
        },
      },
    },
    contact: {
      title: "CONTACT",
      subtitle: "Let's get in touch ._.",
    },
    footer: {
      topLabel: "Top",
      copyrightLabel: "Copyright:",
      quickJumpLabel: "Quick Jump:",
      ascendLabel: "Ascend to Top",
      contactInfoLabel: "Contact Info:",
      craftedByLabel: "Crafted & Aesthetic by:",
    },
    projects: {
      exploreProjectLabel: "Explore Project",
      viewRepositoryLabel: "View Repository",
      noImageAvailableLabel: "No image available",
      noImagesAvailableLabel: "No images available",
      projectOverviewLabel: "Project Overview",
      keyResponsibilitiesLabel: "Key Responsibilities",
      notableAchievementsLabel: "Notable Achievements",
      technicalDetailsLabel: "Technical Details",
      clientLabel: "Client",
      durationLabel: "Duration",
      teamLabel: "Team",
      roleLabel: "Role",
      technologyStackLabel: "Technology Stack",
      multimediaMaterialLabel: "Multimedia Material",
      previousImageLabel: "Previous image",
      nextImageLabel: "Next image",
      teamMemberSingular: "developer",
      teamMemberPlural: "developers",
      monthSingular: "month",
      monthPlural: "months",
      weekSingular: "week",
      weekPlural: "weeks",
      andLabel: "and",
    },
  },
  es: {
    locale: {
      time: "es-MX",
      date: "es-MX",
      duration: "es-MX",
    },
    header: {
      locationLabel: "Ubicacion:",
      navigationLabel: "Navegacion:",
      themeLabel: "Tema:",
      languageLabel: "Idioma:",
      menuLabel: "Menu",
      closeLabel: "Cerrar",
      lightModeLabel: "Modo claro",
      darkModeLabel: "Modo oscuro",
      navigationLinks: [
        { to: "/", label: "Inicio" },
        { to: "/Contact", label: "Contacto" },
        { to: "/Project", label: "Proyectos" },
      ],
    },
    home: {
      about: {
        line1Prefix: "Soy ",
        line1Highlight: "Darinel",
        line1Suffix: ",",
        line2Prefix: "un ",
        line2Highlight: "ingeniero de software versatil",
        line2Suffix: "",
        line3Prefix: "que disfruta del ",
        line3Highlight: "desarrollo full-stack",
        line3Suffix: "",
        line4Prefix: "y la ",
        line4Highlight: "resolucion de problemas",
        line4Suffix: ".",
        notePrefix: "Siempre con ganas de ",
        noteHighlightOne: "aprender y crecer",
        noteMiddle: ", disfruto enfrentar ",
        noteHighlightTwo: "nuevos desafios",
        noteSuffix: " y seguir ampliando mis habilidades.",
      },
      skills: {
        titlePrefix: "Mis",
        titleHighlight: "Habilidades",
        subtitle: "El stack tecnologico que uso para construir soluciones",
        sectionTitles: {
          technical_skills: "Habilidades Tecnicas",
          devOps: "DevOps",
          databases: "Bases de Datos",
          mobile_development: "Desarrollo Movil",
          backend_development: "Desarrollo Backend",
          frontend_development: "Desarrollo Frontend",
          tools: "Herramientas",
          soft_skills: "Habilidades Blandas",
          languages: "Idiomas",
          certifications: "Certificaciones",
        },
      },
    },
    contact: {
      title: "CONTACTO",
      subtitle: "Hablemos ._.",
    },
    footer: {
      topLabel: "Arriba",
      copyrightLabel: "Derechos:",
      quickJumpLabel: "Acceso rapido:",
      ascendLabel: "Subir al inicio",
      contactInfoLabel: "Contacto:",
      craftedByLabel: "Disenado por:",
    },
    projects: {
      exploreProjectLabel: "Explorar proyecto",
      viewRepositoryLabel: "Ver repositorio",
      noImageAvailableLabel: "No hay imagen disponible",
      noImagesAvailableLabel: "No hay imagenes disponibles",
      projectOverviewLabel: "Resumen del proyecto",
      keyResponsibilitiesLabel: "Responsabilidades clave",
      notableAchievementsLabel: "Logros destacados",
      technicalDetailsLabel: "Detalles tecnicos",
      clientLabel: "Cliente",
      durationLabel: "Duracion",
      teamLabel: "Equipo",
      roleLabel: "Rol",
      technologyStackLabel: "Stack tecnologico",
      multimediaMaterialLabel: "Material multimedia",
      previousImageLabel: "Imagen anterior",
      nextImageLabel: "Imagen siguiente",
      teamMemberSingular: "desarrollador",
      teamMemberPlural: "desarrolladores",
      monthSingular: "mes",
      monthPlural: "meses",
      weekSingular: "semana",
      weekPlural: "semanas",
      andLabel: "y",
    },
  },
};
